title: Code
email: codeadoodle@gmail.com
description: "Coding and Stuffs"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codeadoodle.github.io" # the base hostname & protocol for your site
author: "codeadoodle"
twitter_username: 
github_username:  
google_analytics: 'UA-124394-18'

# Build settings
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments    
permalink: /:year/:title/
include: [_pages]
exclude:
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "Gruntfile.coffee"
  - "Rakefile"
  - "README.md"
  - "CHANGELOG.md"
  - "LICENSE"

# More Config
sass:
  compressed: true
# https://github.com/jekyll/jekyll/issues/920
# http://stackoverflow.com/questions/17118551/generating-a-list-of-pages-not-posts-in-a-given-category
# category-list: [featured, projects]
# gems:
# - jekyll-mentions
# - jemoji
# - jekyll-redirect-from
# Prose Config
prose:
  rooturl: '_posts'
  siteurl: 'http://codeadoodle.github.io'
  media: 'assets'
  metadata:
    _posts:
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2015-08-01 00:00:00"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Tutorials"
              value: "tutorials"
            - name: "Articles"
              value: "articles"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
