name: code
description: Blogging about stuffs
meta_description: "Blogging about stuffs"
port: 4003

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://codeadoodle.github.io'
google_analytics: 'UA-124394-18'


# Details for the RSS feed generator
url:            'http://codeadoodle.github.io'
author:         'codeadoodle'
permalink: /posts/:title

# Custom Header Links
about: '/about/'
project: '/projects/'

# Social icons
show_social_icons: true
github_username: codeadoodle
stackoverflow_id:
twitter_username: codeadoodle
google_plus_id:
linkedin_username: codeadoodle
bitcoin_url:
paypal_url:
flattr_button:

# More Config
# redcarpet:
#   extensions: ['smart', 'tables', 'with_toc_data']
sass:
  compressed: true
# https://github.com/jekyll/jekyll/issues/920
include: ['_pages']
# http://stackoverflow.com/questions/17118551/generating-a-list-of-pages-not-posts-in-a-given-category
category-list: [featured, projects]
# gems:
# - jekyll-mentions
# - jemoji
# - jekyll-redirect-from


# Prose Config
prose:
  rooturl: '_posts'
  siteurl: 'http://codeadoodle.github.io'
  media: 'assets'
  metadata:
    _posts:
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2015-08-01 00:00:00"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Tutorials"
              value: "tutorials"
            - name: "Articles"
              value: "articles"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
