# config.yml
backend:
  name: github
  repo: albhardy/albhardy.github.io
  branch: master
  base_url: https://api.netlify.com
  auth_endpoint: auth
# publish_mode: editorial_workflow
media_folder: 'assets/uploads'
collections:
  - name: 'note'
    label: 'Post Note'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: "{{date}} : {{title}}"
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Post Title', name: 'title', widget: 'string' }
      - { label: 'Post Date', name: 'date', widget: 'datetime',date_format: "DD-MM-YYYY",  time_format: false, format: "DD-MM-YYYY"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'select', options: ["ideas", "notes"], default: 'notes'}
      - { label: "Tags", name: "tags", widget: "list",  max: 3, add_to_top: true, allow_add: true, minimize_collapsed: true}
  - name: 'event'
    label: 'Event'
    folder: '_events/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-event-{{slug}}'
    summary: "{{date}} : {{title}}"
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
      - { label: 'Event Title', name: 'title', widget: 'string' }
      - { label: 'Event Date', name: 'date', widget: 'datetime',date_format: "DD-MM-YYYY",  time_format: false, format: "DD-MM-YYYY"}
      - { label: 'Blurb', name: 'blurb', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Tags", name: "tags", widget: "list",  max: 3, add_to_top: true, allow_add: true, minimize_collapsed: true}
  - name: 'project'
    label: 'Project'
    folder: '_projects/'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    summary: "{{date}} : {{title}}"
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Project Order', name: 'orderid', widget: 'number', value_type: 'int'}    
      - { label: 'Project Title', name: 'title', widget: 'string' }
      - { label: 'Project Date', name: 'date', widget: 'datetime',date_format: "YYYY-MM-DD",  time_format: false, format: "YYYY-MM-DD" }
      - { label: 'Blurb', name: 'blurb', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Project Type", name: "project_type", widget: "select", options: ["personal", "work"], default: 'personal' }
      - { label: 'Image Path', name: 'image_path', widget: 'hidden', default: '' }
      - { label: "Tags", name: "tags", widget: "list",  max: 3, add_to_top: true, allow_add: true, minimize_collapsed: true}
    sortable_fields: ['date','orderid','title']
    view_groups:
      - label: Year
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
      - label: Drafts
        field: draft
    view_filters:
      - label: '2020 - 2022 Posts'
        field: date
        pattern: '2020|2021|2022'
      - label: '2017 - 2019 Posts'
        field: date
        pattern: '2017|2018|2019'
      - label: '2014 - 2016 Posts'
        field: date
        pattern: '2014|2015|2016'
      - label: Drafts
        field: draft
        pattern: true
  - name: 'link'
    label: 'Link'
    folder: '_links/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-link-{{slug}}'
    summary: "{{date}} : {{title}}"
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'link' }
      - { label: 'Link Title', name: 'title', widget: 'string' }
      - { label: 'Link Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Link URL', name: 'linkurl', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Tags", name: "tags", widget: "list",  max: 3, add_to_top: true, allow_add: true, minimize_collapsed: true}
  # - name: 'personal_project'
  #   label: 'Project - Personal'
  #   folder: '_projects/'
  #   create: true
  #   slug: '{{year}}-{{month}}-{{slug}}'
  #   filter: {field: "project_type", value: "personal"}
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Image Path', name: 'image_path', widget: 'hidden', default: '' }
  #     - { label: 'Project Order', name: 'orderid', widget: 'number', value_type: 'int'}     
  #     - { label: 'Project Date', name: 'date', widget: 'datetime',date_format: "YYYY-MM-DD",  time_format: false, format: "YYYY-MM-DD" }
  #     - { label: 'Blurb', name: 'blurb', widget: 'string' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  #     - { label: "Project Type", name: "project_type", widget: 'hidden', default: 'personal'}
  #     - { label: "Tags", name: "tags", widget: "list",  max: 3, add_to_top: true, allow_add: true, minimize_collapsed: true}
  #   sortable_fields: ['date','orderid','title']
  #   summary: "{{date}} : {{title}}"
  # - name: 'work_project'
  #   label: 'Project - Work '
  #   folder: '_projects/'
  #   create: true
  #   slug: '{{year}}-{{month}}-{{slug}}'
  #   filter: {field: "project_type", value: "professional"}
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Image Path', name: 'image_path', widget: 'hidden', default: '' }
  #     - { label: 'Project Order', name: 'orderid', widget: 'number', value_type: 'int'}     
  #     - { label: 'Project Date', name: 'date', widget: 'datetime',date_format: "YYYY-MM-DD",  time_format: false, format: "YYYY-MM-DD" }
  #     - { label: 'Blurb', name: 'blurb', widget: 'string' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  #     - { label: "Project Type", name: "project_type", widget: 'hidden', default: 'work'}
  #     - { label: "Tags", name: "tags", widget: "list",  max: 3, add_to_top: true, allow_add: true, minimize_collapsed: true}      
  #   sortable_fields: ['date','orderid','title']
  #   summary: "{{date}} : {{title}}"